---
R1:
  groups: ["cisco_os"]
  hostname: "10.203.8.8"
R2:
  groups: ["cisco_os"]
  hostname: "10.203.8.9"

# Define credentials/platform in a default or group section
groups:
  cisco_os:
    connection_options:
      netmiko:
        extras:
          secret: "secret" # Enable password
    password: "password"
    platform: "cisco_ios"
    username: "admin"
...
